// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace CStore.Web.Areas.Authentication.Controllers
{
    public partial class PasswordController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PasswordController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownloadFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadFile);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PasswordController Actions { get { return MVC.Authentication.Password; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Authentication";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Password";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Password";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Change = "Change";
            public readonly string Expired = "Expired";
            public readonly string DownloadFile = "DownloadFile";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Change = "Change";
            public const string Expired = "Expired";
            public const string DownloadFile = "DownloadFile";
        }


        static readonly ActionParamsClass_Change s_params_Change = new ActionParamsClass_Change();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Change ChangeParams { get { return s_params_Change; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Change
        {
            public readonly string ReturnUrl = "ReturnUrl";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Expired s_params_Expired = new ActionParamsClass_Expired();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Expired ExpiredParams { get { return s_params_Expired; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Expired
        {
            public readonly string ReturnUrl = "ReturnUrl";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DownloadFile s_params_DownloadFile = new ActionParamsClass_DownloadFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadFile DownloadFileParams { get { return s_params_DownloadFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadFile
        {
            public readonly string mimeType = "mimeType";
            public readonly string downloadedFileName = "downloadedFileName";
            public readonly string bytes = "bytes";
            public readonly string dispositionType = "dispositionType";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Change = "Change";
                public readonly string Expired = "Expired";
            }
            public readonly string Change = "~/Areas/Authentication/Views/Password/Change.cshtml";
            public readonly string Expired = "~/Areas/Authentication/Views/Password/Expired.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PasswordController : CStore.Web.Areas.Authentication.Controllers.PasswordController
    {
        public T4MVC_PasswordController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ChangeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ReturnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult Change(string ReturnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Change);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ReturnUrl", ReturnUrl);
            ChangeOverride(callInfo, ReturnUrl);
            return callInfo;
        }

        [NonAction]
        partial void ChangeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, CStore.Domain.Domains.Authentication.Models.ViewModels.Password.ChangePasswordViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Change(CStore.Domain.Domains.Authentication.Models.ViewModels.Password.ChangePasswordViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Change);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ChangeOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ExpiredOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ReturnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult Expired(string ReturnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Expired);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ReturnUrl", ReturnUrl);
            ExpiredOverride(callInfo, ReturnUrl);
            return callInfo;
        }

        [NonAction]
        partial void ExpiredOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, CStore.Domain.Domains.Authentication.Models.ViewModels.Password.ExpiredPasswordViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Expired(CStore.Domain.Domains.Authentication.Models.ViewModels.Password.ExpiredPasswordViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Expired);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ExpiredOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DownloadFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string mimeType, string downloadedFileName, byte[] bytes);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadFile(string mimeType, string downloadedFileName, byte[] bytes)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mimeType", mimeType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "downloadedFileName", downloadedFileName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "bytes", bytes);
            DownloadFileOverride(callInfo, mimeType, downloadedFileName, bytes);
            return callInfo;
        }

        [NonAction]
        partial void DownloadFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string dispositionType, string mimeType, string downloadedFileName, byte[] bytes);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadFile(string dispositionType, string mimeType, string downloadedFileName, byte[] bytes)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dispositionType", dispositionType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mimeType", mimeType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "downloadedFileName", downloadedFileName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "bytes", bytes);
            DownloadFileOverride(callInfo, dispositionType, mimeType, downloadedFileName, bytes);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
